# Generated by Django 4.2 on 2024-03-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_galleryimages_videlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideLinks',
            new_name='VideoLinks',
        ),
    ]
