# Generated by Django 4.2 on 2024-03-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_videlinks_videolinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImages',
        ),
    ]
