# Generated by Django 4.2 on 2024-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_galleryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='name',
            field=models.CharField(default='UmwxncvgvIoTKCfK', max_length=100, unique=True),
        ),
    ]
