# Generated by Django 4.2 on 2024-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_galleryimages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolinks',
            name='name',
            field=models.CharField(default='sdDeevtdyuXLBYUP', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='name',
            field=models.CharField(default='vREKHFOjyCBNSjEd', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videolinks',
            name='link',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
