# Generated by Django 4.2 on 2024-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_galleryimages_name_alter_videolinks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='name',
            field=models.CharField(default='fhbIyQfUErSYvQju', max_length=100, unique=True),
        ),
    ]
