# Generated by Django 4.2 on 2024-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_galleryimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='name',
            field=models.CharField(default='LiHEaHfRUBGftXYf', max_length=100, unique=True),
        ),
    ]
