# Generated by Django 4.2 on 2024-03-12 15:23

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_galleryimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='name',
            field=models.CharField(default=base.models.generate_random_name, max_length=100, unique=True),
        ),
    ]
