# Generated by Django 4.2 on 2024-03-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_galleryimages_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimages',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videolinks',
            name='name',
        ),
    ]
